### ISSUE TITLE
Custom CSS Support or Theme support?

### ISSUE THREAD

**Issue by modjke** [zephyraft/mermaid-previewer#90]
Hey, great extension!
Is there any way to add custom css  or theme support for the rules (auto inject them with the matched rule)? 
https://mermaid.js.org/config/theming.html
There is a minor visual problem displaying graphs on our YouTrack installation (dark mode)
![image](https://github.com/zephyraft/mermaid-previewer/assets/2504184/0a66d097-2034-460d-a80c-92d110bad513)

I can implement that myself and submit a PR, just wanna make sure it will be included in the extension first.

**Comment by modjke** [comment]
I think an ability the injecting a custom theme per domain/rule would be a good addition
```
%%{init: {'theme': 'dark','themeVariables': {'primaryTextColor': '#fff' }}}%%
```

**Comment by zephyraft** [comment]
Thanks, I think that's a good idea. You can try to implement it yourself and contribute a PR.

**Comment by zephyraft** [comment]
Sorry, I misunderstood your needs before. 

In fact, this extension currently supports configuration and custom themes, please refer to 
 https://mermaid.js.org/config/theming.html#customizing-themes-with-themevariables.

According to the official documentation, **if you need to customize the theme, you must use the base theme.**
